// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Seq = require("../src/Seq.bs.js");
var Test = require("rescript-test/src/Test.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");
var TestUtils = require("./TestUtils.bs.js");
var Caml_option = require("rescript/lib/js/caml_option.js");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

var Err = /* @__PURE__ */Caml_exceptions.create("Seq_test.Err");

function unwrap(opt, err) {
  if (opt !== undefined) {
    return Caml_option.valFromOption(opt);
  }
  throw err;
}

function createCharSeq(str) {
  var gen = function (index) {
    var c = str.charAt(index);
    if (c === "") {
      return /* Nil */0;
    } else {
      return Seq.make((function (param) {
                    return gen(index + 1 | 0);
                  }), c);
    }
  };
  return unwrap(gen(0), {
              RE_EXN_ID: Err,
              _1: "createCharSeq: unexpected"
            });
}

Test.test("test seq of 'abc'", (function (param) {
        var seq = createCharSeq("abc");
        if (!seq) {
          return Test.fail("first is nil", undefined);
        }
        var c = seq._0;
        var first = Seq.car(c);
        var seq$1 = Seq.cdr(c);
        TestUtils.stringEqual("first is a", first, "a");
        if (seq$1 === undefined) {
          return Test.fail("second is nil", undefined);
        }
        if (!seq$1) {
          return Test.fail("second is nil", undefined);
        }
        var c$1 = seq$1._0;
        var second = Seq.car(c$1);
        var seq$2 = Seq.cdr(c$1);
        TestUtils.stringEqual("second is b", second, "b");
        if (seq$2 === undefined) {
          return Test.fail("third is nil", undefined);
        }
        if (!seq$2) {
          return Test.fail("third is nil", undefined);
        }
        var c$2 = seq$2._0;
        var second$1 = Seq.car(c$2);
        var seq$3 = Seq.cdr(c$2);
        TestUtils.stringEqual("third is c", second$1, "c");
        return Test.assertion("seq should end", undefined, Caml_obj.caml_equal, seq$3, /* Nil */0);
      }));

Test.test("test seq match", (function (param) {
        var seq = createCharSeq("abc");
        TestUtils.seqEqual("seq match should be 3", seq, {
              hd: "a",
              tl: {
                hd: "b",
                tl: {
                  hd: "c",
                  tl: /* [] */0
                }
              }
            });
        var arr = Seq.fromArrayInPlace([
              "a",
              "b",
              "c"
            ]);
        TestUtils.seqEqual("array inplace seq match should be 3", arr, {
              hd: "a",
              tl: {
                hd: "b",
                tl: {
                  hd: "c",
                  tl: /* [] */0
                }
              }
            });
        var arr$1 = Seq.fromArray([
              "a",
              "b",
              "c"
            ]);
        return TestUtils.seqEqual("array seq match should be 3", arr$1, {
                    hd: "a",
                    tl: {
                      hd: "b",
                      tl: {
                        hd: "c",
                        tl: /* [] */0
                      }
                    }
                  });
      }));

Test.test("test seq append", (function (param) {
        var s1 = Seq.fromArray([
              1,
              2
            ]);
        var s2 = Seq.fromArray([3]);
        return TestUtils.seqEqual("seq 1 2 + seq 3, is seq 1 2 3", Seq.append(s1, (function (param) {
                          return s2;
                        })), {
                    hd: 1,
                    tl: {
                      hd: 2,
                      tl: {
                        hd: 3,
                        tl: /* [] */0
                      }
                    }
                  });
      }));

Test.test("test seq merge", (function (param) {
        var s1 = Seq.fromArray([
              1,
              2
            ]);
        var s2 = Seq.fromArray([3]);
        TestUtils.seqEqual("seq 1 2 merge seq 3, is seq 1 3 2", Seq.merge(s1, s2), {
              hd: 1,
              tl: {
                hd: 3,
                tl: {
                  hd: 2,
                  tl: /* [] */0
                }
              }
            });
        var s1$1 = Seq.fromArray([1]);
        var s2$1 = Seq.fromArray([
              2,
              3
            ]);
        TestUtils.seqEqual("seq 1 merge seq 2 3, is seq 1 2 3", Seq.merge(s1$1, s2$1), {
              hd: 1,
              tl: {
                hd: 2,
                tl: {
                  hd: 3,
                  tl: /* [] */0
                }
              }
            });
        var s1$2 = Seq.fromArray([1]);
        var s2$2 = Seq.fromArray([
              2,
              3,
              4
            ]);
        TestUtils.seqEqual("seq 1 merge seq 2 3 4, is seq 1 2 3 4", Seq.merge(s1$2, s2$2), {
              hd: 1,
              tl: {
                hd: 2,
                tl: {
                  hd: 3,
                  tl: {
                    hd: 4,
                    tl: /* [] */0
                  }
                }
              }
            });
        var s1$3 = Seq.fromArray([
              1,
              2,
              3
            ]);
        var s2$3 = Seq.fromArray([4]);
        return TestUtils.seqEqual("seq 1 2 3 merge seq 4, is seq 1 2 3 4", Seq.merge(s1$3, s2$3), {
                    hd: 1,
                    tl: {
                      hd: 4,
                      tl: {
                        hd: 2,
                        tl: {
                          hd: 3,
                          tl: /* [] */0
                        }
                      }
                    }
                  });
      }));

function createInfinitSeq(i) {
  return Seq.cons(i, {
              TAG: /* Lazy */1,
              _0: (function (param) {
                  return createInfinitSeq(i + 1 | 0);
                })
            });
}

Test.test("infinit seq take 3", (function (param) {
        var seq = createInfinitSeq(0);
        var first3 = Seq.take(seq, 3);
        TestUtils.seqEqual("take first 3 from infinit list", first3, {
              hd: 0,
              tl: {
                hd: 1,
                tl: {
                  hd: 2,
                  tl: /* [] */0
                }
              }
            });
        var first3$1 = Seq.lazyTake(seq, 3);
        TestUtils.seqEqual("lazyTake first 3 from infinit list", first3$1, {
              hd: 0,
              tl: {
                hd: 1,
                tl: {
                  hd: 2,
                  tl: /* [] */0
                }
              }
            });
        var first3$2 = Seq.takeWhile(seq, (function (v) {
                return v < 3;
              }));
        TestUtils.seqEqual("takeWhile v < 3 from infinit list", first3$2, {
              hd: 0,
              tl: {
                hd: 1,
                tl: {
                  hd: 2,
                  tl: /* [] */0
                }
              }
            });
        var first3$3 = Seq.lazyTakeWhile(seq, (function (v) {
                return v < 3;
              }));
        return TestUtils.seqEqual("lazyTakeWhile v < 3 from infinit list", first3$3, {
                    hd: 0,
                    tl: {
                      hd: 1,
                      tl: {
                        hd: 2,
                        tl: /* [] */0
                      }
                    }
                  });
      }));

Test.test("infinit seq map + 1", (function (param) {
        var seq = createInfinitSeq(0);
        var first3 = Seq.map(Seq.take(seq, 3), (function (v) {
                return v + 1 | 0;
              }));
        TestUtils.seqEqual("map v + 1 after take first 3 from infinit list", first3, {
              hd: 1,
              tl: {
                hd: 2,
                tl: {
                  hd: 3,
                  tl: /* [] */0
                }
              }
            });
        var first3$1 = Seq.take(Seq.lazyMap(seq, (function (v) {
                    return v + 1 | 0;
                  })), 3);
        return TestUtils.seqEqual("lazyMap v + 1 before take first 3 from infinit list", first3$1, {
                    hd: 1,
                    tl: {
                      hd: 2,
                      tl: {
                        hd: 3,
                        tl: /* [] */0
                      }
                    }
                  });
      }));

exports.Err = Err;
exports.unwrap = unwrap;
exports.createCharSeq = createCharSeq;
exports.createInfinitSeq = createInfinitSeq;
/*  Not a pure module */
