// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Seq = require("../src/Seq.bs.js");
var List = require("rescript/lib/js/list.js");
var Test = require("rescript-test/src/Test.bs.js");
var Caml_obj = require("rescript/lib/js/caml_obj.js");
var Belt_Array = require("rescript/lib/js/belt_Array.js");

var identity = Caml_obj.caml_equal;

function intEqual(message, a, b) {
  return Test.assertion(message, "intEqual", identity, a, b);
}

function stringEqual(message, a, b) {
  return Test.assertion(message, "stringEqual", identity, a, b);
}

function seqEqual(message, seq, lst) {
  var len1 = List.length(lst);
  var mathcer = Seq.fromList(lst);
  var ret = Seq.match(undefined, seq, mathcer);
  var match = Seq.countForced(seq);
  Test.assertion("[seq is forced]", "seqEqual", identity, match[1], true);
  Test.assertion("[length is equal]", "seqEqual", identity, match[0], len1);
  return Test.assertion(message, "seqEqual", identity, ret, len1);
}

function arrayEqual(message, a, b, comp) {
  return Test.assertion(message, "arrayEqual", (function (a, b) {
                return Belt_Array.eq(a, b, comp);
              }), a, b);
}

exports.identity = identity;
exports.intEqual = intEqual;
exports.stringEqual = stringEqual;
exports.seqEqual = seqEqual;
exports.arrayEqual = arrayEqual;
/* Test Not a pure module */
