// Generated by ReScript, PLEASE EDIT WITH CARE
'use strict';

var Seq_Core = require("./Seq_Core.bs.js");
var Caml_exceptions = require("rescript/lib/js/caml_exceptions.js");

var Err = /* @__PURE__ */Caml_exceptions.create("Seq_Slice.Err");

function car(slice) {
  var seq = slice[1];
  if (seq) {
    return Seq_Core.car(seq._0);
  }
  throw {
        RE_EXN_ID: Err,
        _1: "unexpected slice, which is Nil.",
        Error: new Error()
      };
}

function cdr(slice) {
  var len = slice[0];
  if (len === 0) {
    throw {
          RE_EXN_ID: Err,
          _1: "unexpected slice, which is 0 length.",
          Error: new Error()
        };
  }
  var seq = slice[1];
  if (seq) {
    return [
            len - 1 | 0,
            Seq_Core.cdr(seq._0)
          ];
  }
  throw {
        RE_EXN_ID: Err,
        _1: "unexpected slice, which is Nil.",
        Error: new Error()
      };
}

function toSeq(slice) {
  return Seq_Core.take(slice[1], slice[0]);
}

function toLazySeq(slice) {
  return Seq_Core.lazyTake(slice[1], slice[0]);
}

function seqSplitUnsafe(seq, n) {
  return [
          [
            n,
            seq
          ],
          Seq_Core.drop(seq, n)
        ];
}

function seqSplitWhile(seq, test) {
  var match = Seq_Core.dropWhile(seq, test);
  return [
          [
            match[0],
            seq
          ],
          match[1]
        ];
}

exports.Err = Err;
exports.car = car;
exports.cdr = cdr;
exports.toSeq = toSeq;
exports.toLazySeq = toLazySeq;
exports.seqSplitUnsafe = seqSplitUnsafe;
exports.seqSplitWhile = seqSplitWhile;
/* No side effect */
